### ISSUE TITLE
Reporting server v2 CEL environment does not contain v2 event group descriptor and list event groups with filter option fail (v0.4.2)

### ISSUE THREAD

**Issue by BaibaSku** [world-federation-of-advertisers/cross-media-measurement#1406]
**Describe the bug**
(v0.4.2) When calling list event groups with filter on reporting server v2 and using fields, which are relevant to event group (v2) only (cmms_data_provider field as an example), the request fails, with following error message:

>   _INVALID_ARGUMENT: filter is not a valid CEL expression: ERROR: <input>:1:1: undeclared reference to 'cmms_data_provider' (in container 'wfa.measurement.reporting.v1alpha.EventGroup')\n | cmms_data_provider == 'dataProviders/a0tmyormbgQ'_

**Steps to reproduce**
1. Call list event groups on reporting server v2 by using cel expression, which contains v2 Event group field. Example:cmms_data_provider == 'dataProviders/a0tmyormbgQ'

**Component(s) affected**
Reporting Server

**Version**
0.4.2

**Comment by mariolamassaavedra** [comment]
This error seems to be cause due to the [CEL Env Provider](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/v0.4.2/src/main/kotlin/org/wfanet/measurement/reporting/service/api/CelEnvProvider.kt)  not importing the Reporting Server v2 definition of the event groups object and only referencing v1 
![image](https://github.com/world-federation-of-advertisers/cross-media-measurement/assets/61779113/ab40a549-ca16-408c-af77-c518fbf58797)

**Comment by SanjayVas** [comment]
@tristanvuong2021 can you take a look at this? We probably need separate CelEnvProvider impls for v1 and v2, given that it depends on an API message.
