### ISSUE TITLE
editVersion mismatch in RecordOutputBlobPath

### ISSUE THREAD

**Issue by SanjayVas** [world-federation-of-advertisers/cross-media-measurement#680]
Digging into an error that I sometimes (but not always) see popping up in the integration test. It shows up as `TRANSIENT` error in the LLv2 Mill. The source appears to be `GcpSpannerComputationsDatabaseTransactor`. Adding more logging gives the following:

```
wfa.measurement.internal.duchy.Computations RecordOutputBlobPath
WARNING: [DefaultDispatcher-worker-2 @coroutine#3852] gRPC error: UNKNOWN
java.lang.IllegalStateException: Failed to update because of editVersion mismatch.
  Token's editVersion: 1662062844075 (2022-09-01T20:07:24.075Z)
  Computations table's UpdateTime: 1662062846260 (2022-09-01T20:07:26.260354Z)
  Difference: PT2.185354S
	at org.wfanet.measurement.duchy.deploy.gcloud.spanner.computation.GcpSpannerComputationsDatabaseTransactor$runIfTokenFromLastUpdate$2.invokeSuspend(GcpSpannerComputationsDatabaseTransactor.kt:690)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by wangyaopw** [comment]
This might not be a bug.

By design, the worker who owns the computation can update it only if the computation hasn't been modified by someone else.

For example, if the worker's lock on this computation expires, the computation could be claimed by another worker and gets updated, or maybe the computation is marked FAILED by the herald. Once a computation is updated by someone else, the original worker who claimed it won't be able to update it again.

Such failure is transient and this worker will simply give up current attempt.

**Comment by wangyaopw** [comment]
Disclaimer: this logic is not designed by me.

**Comment by renjiezh** [comment]
> This might not be a bug.
> 
> By design, the worker who owns the computation can update it only if the computation hasn't been modified by someone else.
> 
> For example, if the worker's lock on this computation expires, the computation could be claimed by another worker and gets updated, or maybe the computation is marked FAILED by the herald. Once a computation is updated by someone else, the original worker who claimed it won't be able to update it again.
> 
> Such failure is transient and this worker will simply give up current attempt.

Thank you Yao for the explanation.
I don't really get "another worker". I guess the Computation we discussed about here is the local Computation, which will only be accessed by the single worker. Do you mean "another thread" of the worker?

**Comment by wangyaopw** [comment]
A worker means a pod of the mill.

Oh, if this log is from the integrationTest, then it is not due to a mill losing its claim to a computation, since we only have 1 mill in each inProcessDuchy.

Other scenario that can cause this error is in the AsyncComputationControlService, where the non-aggregators send their initial sketches to the aggregator at the same time, handlerA reads the token and then handlerB read the same token, handlerA then writes the path and causes the updateTime to change, when handlerB tries to write, it would fail.

There aren't many cases in which the updateTime of the computation can change during someone else is trying to update it.
