### ISSUE TITLE
Use structured logging for Google Cloud Logging

### ISSUE THREAD

**Issue by mariolamassaavedra** [world-federation-of-advertisers/cross-media-measurement#762]
All Halo's logging is captured as ERROR by the GCP log tooling. This makes debugging complicated and hard to understand what is going on

- [ ] https://github.com/world-federation-of-advertisers/common-jvm/pull/220
- [ ] #1332

**Comment by SanjayVas** [comment]
This is specific to Google Cloud Logging. Unless you use the Cloud Logging structured logging API, everything uses the default level of "Error". The actual logging level is indicated in the log content.

This is WAI in terms of how Cloud Logging works, but we can use the Cloud Logging structured logging API as an enhancement. Note that this work would be specific to Google Cloud.

**Comment by SanjayVas** [comment]
Since we have to support multiple cloud platforms, ideally this is something that can be done without having to create separate GCloud binaries for everything. For example, our public API server is currently platform-agnostic.

The easiest option implementation-wise would likely be https://cloud.google.com/logging/docs/setup/java#the_javautillogging_handler, since all of our Kotlin JVM code uses java.util.logging. This would likely have the separate binary problem mentioned above, however.

There might be an option of having our logging go through some platform-agnostic format (Fluentd?) and having an agent that reads that format. This avoids having separate binaries, but may mean self-hosting another Deployment in GKE.
