### ISSUE TITLE
Event Group Reference ID

### ISSUE THREAD

**Issue by mariolamassaavedra** [world-federation-of-advertisers/cross-media-measurement#765]
The original Halo design intended to use the reference id as key identifier for the event groups which were expected to be available within the requisitions. The implementation is different and the reference id ended up being unused
The ability to have a reference id for EDPs would be useful

**Comment by SanjayVas** [comment]
> The original Halo design intended to use the reference id as key identifier for the event groups which were expected to be available within the requisitions

This is not true. All API references have always intended to be done via resource names, as described in the AIPs. There was an incorrect statement made in one of the Event Group design docs that stated reference ID instead of resource name. Reference IDs were only ever intended for use as reference. See Slack thread: https://cross-mediaworkspace.slack.com/archives/C0312M4HE3F/p1669212664806139

> The ability to have a reference id for EDPs would be useful

API references will never use anything other than resource names, as that's laid out by the AIPs. Reference IDs can be used in Event Group search via ListEventGroups in order to look up EventGroup resource names, which can then be used in the API.
