### ISSUE TITLE
Error when calling CMMS public API using Duchy credentials

### ISSUE THREAD

**Issue by dprao88** [world-federation-of-advertisers/cross-media-measurement#855]
**Describe the bug**
As Duchy certs in prod(kingdom) are expired, we were trying to rotate the duchy certificate and we got an UnKnown error. Also, throws UnKnown when we tried calling getCertificate of particular duchy. Please find the below screenshot of error message.
<img width="947" alt="image" src="https://user-images.githubusercontent.com/122367168/218453288-7bf48c3f-b7aa-4ea5-94ef-b4df5503238a.png">

**Steps to reproduce**
1. Call the GetCertificate methos with valid duchy certs.
2. Call the CreateCertificate method with valid duchy certs.

**Component(s) affected**
Kingdom, Duchy

**Version**
Prod- b3af7ed4161f31077eaafb6cfddc58dd1ad956f0
76a0129905033aaabd98f0cecd5462a11551e921

**Environment**
We observed in Prod (kingdom) and QA (Dev). 

**Additional context**
Please find the following logs which are related to the error. (We tried GetCertificate method in Halo's env as well and got the same UnKnown error)
<img width="729" alt="image" src="https://user-images.githubusercontent.com/122367168/218458961-70a8e05d-4055-4f5c-a2b6-ad9f7b3c254d.png">
<img width="691" alt="image" src="https://user-images.githubusercontent.com/122367168/218459243-5465f570-1288-4af8-970f-f3a6fd02f9fa.png">

Please let us know for more details. Thank you.

**Comment by SanjayVas** [comment]
This was discussed on https://cross-mediaworkspace.slack.com/archives/C0312M4HE3F/p1675952877842359 and this does not appear to be a bug, but rather a misconfiguration.

The error is being thrown from code that loads `duchy_cert_config.textproto`. This could be caused by e.g. a malformed file or something being wrong with the secret that the file is read from.

Since this is a server misconfiguration, there is not really any useful error information to be given to the API user. `INTERNAL` might be more accurate.

**Comment by SanjayVas** [comment]
Re-opening this after offline discussion. The issue is not entirely as described. It has nothing to do with GetCertificate nor configuration, but rather calling the CMMS public API using Duchy credentials. The public API server doesn't even load the config.

**Comment by SanjayVas** [comment]
The correctness test does not exercise this path as the Duchy gets what is needs from the system API. This path is only used when Duchy operators need to interact with their consent signaling certificates.
