### ISSUE TITLE
Herald should be able to fail a computation if necessary.

### ISSUE THREAD

**Issue by wangyaopw** [world-federation-of-advertisers/cross-media-measurement#87]
Currently, the herald just processes kingdom updates one by one, if it fails to process a computation it would retry. It is not possible to skip a computation if it fails indefinitely. 

We need to allow the herald to permanently fail a computation locally and update to the kingdom if necessary.

**Comment by SanjayVas** [comment]
It should be possible to update the Kingdom using the `ComputationLogEntries` service. Adding a log entry with an error type of `PERMANENT` should put the parent Computation into the `FAILED` state.

See [computation_log_entry.proto](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e65a7856f51338d98d94ea1d140ea3eab616bc1f/src/main/proto/wfa/measurement/system/v1alpha/computation_log_entry.proto#L78).

**Comment by wangyaopw** [comment]
I would prefer to add another method in the ComputationsService.

It is a little weird to call one service to set computation result, and call another one to fail a computation. Using ComputationLogEntriesService to fail a computation is like a side effect of logging an error.

**Comment by SanjayVas** [comment]
I don't think another method is needed, given the following two properties:

1. If there's a `ComputationLogEntry` indicating a permanent failure, the `Computation` should be in the `FAILED` state. Otherwise, the state is inconsistent.
2. If the `Computation` has failed due to an unexpected error from a Duchy, there should be a corresponding `ComputationLogEntry`.

An alternative is to drop the error type from `ComputationLogEntry` and instead have failure information stored in the `ComputationParticipant`. This would be closer to how Requisition refusal works, where the Requisition has refusal details and refusing a Requisition fails the parent Computation/Measurement.

**Comment by wangyaopw** [comment]
I like the idea of moving the permanent failure to ComputationParticipant.

**Comment by SanjayVas** [comment]
CC @efoxepstein who initially added report log entries.

**Comment by efoxepstein** [comment]
I feel like we want to track error types in `ComputationLogEntry` too to make it easier to correlate log entries with what went wrong. That said, we could keep the source of truth for the current state at the `ComputationParticipant` level.

**Comment by wangyaopw** [comment]
FYI, currently all logging rpcs from the duchy to the kingdom are try-and-ignore-failure style. In other words, if a CreateComputationLogEntry rpc fails, the mill won't revert local changes and retry again later.

When we use the ComputationParticipant to fail a computation, we need to make sure the rpc succeeds.
